### ISSUE TITLE
Unexpected operator errors

### ISSUE THREAD

**Issue by mark2741** [terminalforlife/ubuntu-syschk#1]
Receiving the following output when trying to run the stable build on Linux Mint 18.3 64-bit Cinnamon:

mark@mark-mint ~/Downloads/ubuntu-syschk-master $ sh ubuntu-syschk --verbose
ubuntu-syschk: 15: [: true: unexpected operator
ubuntu-syschk: 157: [: unexpected operator
ubuntu-syschk: 159: [: unexpected operator
ubuntu-syschk: 160: [: unexpected operator
ubuntu-syschk: 167: ubuntu-syschk: Syntax error: "(" unexpected (expecting "then")

**Comment by terminalforlife** [comment]
Thanks for the report, Mark. This is a case of user error, however. :) You're using sh to run a bash program. If you're looking for a one-off execution, I suggest:

```
bash ubuntu-syschk --verbose
```

Or install it using insit:

```
sudo insit ubuntu-syschk
```

Then you need only run this it like any other program (without prefixing the command with "bash")

**Comment by mark2741** [comment]
Got it. Thanks so much!
